/**
 * GitHub Flavored Markdown Heading ID Extension for Marked
 *
 * Forked from: https://github.com/markedjs/marked-gfm-heading-id (v4.1.3)
 * Original license: MIT
 *
 * =============================================================================
 * WHY WE FORKED
 * =============================================================================
 *
 * The original package only provides the heading ID. We need more for TOC
 * generation: both the formatted text (with HTML) AND the plain text.
 *
 * HeadingData provides two representations:
 *
 *   text: "Using <code>npm install</code>"   ← HTML preserved (for TOC links)
 *   raw:  "Using npm install"                ← Plain text (for slug generation)
 *
 * Example: Markdown heading `## Using \`npm install\``
 *
 *   1. marked renders: "Using <code>npm install</code>"
 *   2. We store this as `text` (used in TOC link display)
 *   3. We strip HTML + decode entities → `raw` (used for ID generation)
 *   4. github-slugger creates ID from raw → "using-npm-install"
 *
 * The TOC then shows formatted links:
 *
 *   <a href="#using-npm-install">Using <code>npm install</code></a>
 *
 * Without our fork, TOC links would lose all formatting:
 *
 *   <a href="#using-npm-install">Using npm install</a>  ← formatting lost!
 *
 * =============================================================================
 * CHANGES FROM ORIGINAL
 * =============================================================================
 *
 * - Converted to TypeScript
 * - Simplified API (removed globalSlugs option - we always reset per document)
 * - Added `text` field: HTML as rendered by marked (preserves <code>, <strong>, etc.)
 * - Added `raw` field: Plain text with HTML stripped and entities decoded
 * - Slug generation uses `raw` (decoded text, not HTML)
 */

import GithubSlugger from 'github-slugger';
import type { MarkedExtension, Tokens } from 'marked';
import { decodeHtmlEntities, stripHtmlTags } from './html.utils';

export interface HeadingData {
  /** Heading level (1-6) */
  level: number;
  /** Formatted text with HTML preserved: "Using <code>npm</code>" */
  text: string;
  /** Plain text (HTML stripped, entities decoded): "Using npm" */
  raw: string;
  /** Anchor ID for linking: "using-npm" (generated by github-slugger) */
  id: string;
}

let slugger = new GithubSlugger();
let headings: HeadingData[] = [];

/**
 * Create a marked extension that adds GitHub-style heading IDs.
 *
 * @param options.prefix - Optional prefix for all heading IDs
 * @returns MarkedExtension to pass to marked.use()
 *
 * @example
 * ```typescript
 * const marked = new Marked(gfmHeadingId());
 * marked.parse('# Hello World');
 * // <h1 id="hello-world">Hello World</h1>
 * ```
 */
export function gfmHeadingId({ prefix = '' } = {}): MarkedExtension {
  return {
    hooks: {
      preprocess(src: string): string {
        // Always reset for each document (we process one doc at a time)
        resetHeadings();
        return src;
      },
    },
    renderer: {
      heading({ tokens, depth }: Tokens.Heading): string {
        // Get the rendered HTML text (may contain HTML entities and tags)
        // @ts-ignore - 'this' context is provided by marked at runtime
        const text: string = this.parser.parseInline(tokens);

        // Get raw text: decode entities, strip HTML tags
        const raw = stripHtmlTags(decodeHtmlEntities(text)).trim();

        const level = depth;
        const id = `${prefix}${slugger.slug(raw)}`;

        headings.push({ level, text, id, raw });

        return `<h${level} id="${id}">${text}</h${level}>\n`;
      },
    },
  };
}

/**
 * Get the list of headings collected during the last parse.
 * Call this after marked.parse() to get heading data for TOC generation.
 */
export function getHeadingList(): HeadingData[] {
  return headings;
}

/**
 * Reset the heading list and slugger.
 * Called automatically in preprocess hook, but can be called manually if needed.
 */
export function resetHeadings(): void {
  headings = [];
  slugger = new GithubSlugger();
}
